@startuml

class Usuario {
    - id: int
    - nombre: String
    - email: String
    - contraseña: String
    - perfilVerificado: Boolean
}

class Profesor extends Usuario {
    - especialidad: String
    - formacionAcademica: String
    - experiencia: String
    - calificacion: Float
    - reseñas: List<String>
    + publicarCurso()
    + obtenerInformacion(): String
}

class Estudiante extends Usuario {
    - nivelEducativo: String
    + buscarProfesor()
    + calificarProfesor()
    + programarSesion()
}

class EstudianteGestiona {
    + verInformacion()
    + modificarInformacion()
    + eliminarCuenta()
    + buscarProfesor()
    + reservarTurno()
    + cancelarTurno()
    + calificarProfesor()
    + comprarCurso()
    + crearPosteoComunidad()
    + crearPostulacionTutor()
    + gestionarPerfil()
    + visualizarHistorialTransacciones()
    + contactarSoporteTecnico()
    + gestionarPreferenciasComunicacion()
    + recuperarContraseñaOlvidada()
}

class ProfesorGestiona {
    + verInformacion()
    + modificarInformacion()
    + eliminarCuenta()
    + cargarFormacionAcademica()
    + calificarAlumno()
    + subirCurso()
    + solicitarVerificacionPerfil()
    + programarSesionTutoria()
    + visualizarEstadisticasDesempeño()
    + generarReporteActividad()
    + solicitarSoporteTecnico()
    + generarActividadComunitaria()
}

class Curso {
    -id: int
    - titulo: String
    - descripcion: String
    - precio: Float
    + obtenerInformacion(): String
}

class Reserva {
    - id: int
    - fecha: Date
    - hora: Time
    - duracion: int
    + confirmar()
    + cancelar()
}

class Comunidad {
    -id: int
    -contenido: List<Posteo>
    + contribuirEjercicios()
    + contribuirMaterialEstudio()
}

class Posteo {
    - id: int
    - contenido: String
}

class CorreoElectronico {
    - id: int
    - direccion: String
    - contenido: String
}

class Pago{

    -id: int
    -monto: Float
    -fecha: Date

}

class TicketST{

    -id: int
    -fecha: Date
    -tipo: String
    -estado: String
    -descripcion: String
}

class Publicidad {
    - id: int
    - tipo: String
    - fechaCaducidad: Date
    - alcance: String
    + mostrarAnuncio()
}

class Suscripcion {
    -id: int
    -fechaVencimiento: Date
    -renovAuto: Boolean
    - tarifa: Float
    + obtenerBeneficios(): String
}

Profesor "1" -- "1" ProfesorGestiona
Profesor "1" -- "0..1" Curso
Profesor "1" -- "n" Reserva
Profesor "1" -- "0..n" Publicidad
Profesor "1" -- "0..n" Comunidad
Estudiante "1" -- "1" EstudianteGestiona
Estudiante "1" -- "n" Reserva
Estudiante "1" -- "0..n" Comunidad
Estudiante "1" -- "0..1" Suscripcion
Usuario "1" -- "n" CorreoElectronico
Usuario "1" -- "n" Pago
Usuario "1" -- "n" TicketST
Comunidad "1" -- "n" Posteo


@enduml
